import type { Industry } from './types'

/**
 * Titles, slugs and meta descriptions are locked copy from the current site.
 * Everything else is supporting copy written for the rebuild against a fixed rule
 * set — no invented statistics, no named editors, no placement guarantees, no
 * claimed affiliation with any publication. See CONTENT-NOTES.md.
 */
export const industries: Industry[] = [
  {
    slug: 'startups',
    title: 'PR for Startups',
    navLabel: 'Startups',
    description: 'Press coverage for startup founders — what it does for fundraising and hiring, where we place clients, and how the process works.',
    audience: 'For founders building something early — pre-seed through Series A — who need investors, candidates and first customers to take them seriously before there is a track record to point at.',
    intro: [
      'Nobody has heard of you yet. That is the normal condition of an early company, and it is also the thing that quietly costs you — the investor who takes a meeting and then searches, the senior hire deciding whether you are real, the first customer who has to explain the choice to a boss.',
      'We write and place the article that answers them. You fill in a short questionnaire, our editorial team drafts the piece, and you keep revising until it reads the way you would say it. Nothing publishes without your approval.',
    ],
    whyItWorks: [
      'Investors search you between the first call and the partner meeting. With no long operating history to read, what comes up in that search — a real article explaining what you are building and why — carries a lot of the impression you make.',
      'Good engineers are leaving stable jobs to join you. They check whether the company exists anywhere outside its own website, and so does the person they live with.',
      'A funding announcement gets one news cycle and then scrolls away. The feature written around it keeps working, and it is still there when a customer looks you up months later.',
      "Your first serious customers have to defend the choice internally. Buying from an unknown company is a risk with somebody's name attached to it, and independent coverage makes that easier to carry.",
    ],
    outlets: [
      'Entrepreneur',
      'Business Insider',
      'Fast Company',
      'Inc.',
      'Yahoo Finance',
      'Benzinga',
    ],
    angles: [
      { title: 'Why you left', body: 'The job you walked away from and the problem that made you do it. Editors run founder stories when the decision is specific — the thing you kept seeing that nobody was fixing — not when the piece opens with a product description.' },
      { title: 'The round, explained', body: 'A raise is news for about a day. The version that lasts explains what the money is actually for, what you got wrong in the year before it, and what has to be true for the thesis to work. That reads as candor, and candor gets published.' },
      { title: 'What early users changed', body: 'The feature you were certain about that nobody used, and what the first customers made you rebuild. Founders rarely publish this, which is exactly why it lands — it gives a reader something to use instead of something to admire.' },
      { title: 'The contrarian read', body: 'Everyone in your category repeats the same assumption. You have been close enough to the work to know where it breaks, and you can say so with your name attached. Opinion pieces travel further than announcements, and they are the ones investors forward.' },
    ],
    objection: 'The honest version: at the earliest stage, press does not create demand that is not there. If you have a landing page and no product, wait. What press does is close the gap between somebody hearing your name and somebody trusting it — and that gap opens the moment you start raising or hiring, whether you have published anything or not.',
  },
  {
    slug: 'saas-companies',
    title: 'PR for SaaS Companies',
    navLabel: 'SaaS Companies',
    description: 'Press coverage for SaaS founders and companies — building category credibility, where we place clients, and how the process works.',
    audience: 'For SaaS founders and marketing leads selling software that gets researched, compared and signed off by more than one person before anybody pays.',
    intro: [
      'Software gets bought slowly and by committee. Somewhere between the demo and the signature, people who were never on the call go looking — a finance lead, a security reviewer, the executive whose budget it is — and what they find decides how much friction the deal carries.',
      'Coverage is what they find. We shape the story, our editorial team writes it to the standard the publication expects, and you revise it until the positioning is right. You approve the final piece before it goes anywhere.',
    ],
    whyItWorks: [
      'Your champion has to sell you internally to people you never meet. A link to a real article on a publication their finance lead recognizes does work inside that room that your own case study page cannot.',
      "Buyers compare before they book a demo. When someone searches your name against a competitor's, they find your site, review listings, and whatever else exists — press is the only part of that set written by someone other than a vendor.",
      'Answer engines summarize categories now, and they summarize from what has been published. Being described in editorial coverage as one of the companies doing this work is how you end up inside that summary rather than absent from it.',
      'Category language gets set before the market settles on it. If you are defining a new way of doing something, the words used in print tend to become the words buyers use in procurement.',
    ],
    outlets: [
      'Business Insider',
      'Fast Company',
      'MarketWatch',
      'Yahoo Finance',
      'The Business Journals',
      "Int'l Business Times",
    ],
    angles: [
      { title: 'The category thesis', body: 'Not what your product does, but why the standard way of doing this is quietly breaking. The strongest SaaS features argue a position about the category and let the product appear as evidence. It also gives every future article something to build on.' },
      { title: 'What your data sees', body: 'Your product sits close to how your customers actually work, and you can see patterns nobody outside can. Written up plainly — with your own real figures if you are willing to share them — it is the kind of piece editors take, because the evidence is first-hand.' },
      { title: 'The pricing rewrite', body: 'Moving off seats, killing a plan, publishing your rates after years of quoting them: pricing decisions are unusually readable, because every other founder in software is wrestling with the same call. Say what it cost you and the piece writes itself.' },
      { title: 'How to evaluate this', body: "A buyer's guide to your own category, written straight, including the cases where a tool like yours is the wrong answer. Your champion forwards it to the committee. Honesty about your own limits is the part that makes the rest believable." },
    ],
    objection: 'Fair: you will not see this in last-click, and anyone promising you a pipeline number from a feature is guessing. Press works in the part of the cycle you cannot instrument — the search before the demo, the deck your champion builds, the security review. If your product is low-cost and self-serve, and nobody researches before signing up, spend the money on acquisition instead.',
  },
  {
    slug: 'coaches',
    title: 'PR for Coaches',
    navLabel: 'Coaches',
    description: 'Press coverage for coaches and consultants — building the authority clients check for, where we place features, and how it works.',
    audience: 'For coaches and consultants — executive, business, health, career — whose clients pay a real fee to work with a person, and who look that person up first.',
    intro: [
      'Your buyer meets you on a podcast, a stage or a feed, likes you, and then goes looking. What they find in the next few minutes decides whether the call gets booked — and for most coaches, all of it is self-published.',
      "Press is the part somebody else wrote. We develop the angle, our editorial team writes the piece to the outlet's standard, and you revise it until it sounds like you rather than like a bio. Nothing goes live until you say so.",
    ],
    whyItWorks: [
      'There is no license to check. Your field has no board and no registry, so a prospective client verifies you the only way available to them: they search your name and read what comes back.',
      'The gap between the discovery call and the deposit is where you lose people. A permanent article on a publication they have heard of gives them something to point at when they justify the decision to a spouse or a manager.',
      'Podcast hosts, conference organizers and corporate training buyers vet you before they book. Published features give them a reason to say yes and a bio they can copy without asking you for one.',
      'Referrals still get looked up. When somebody recommends you, the person they sent finds either your own funnel or evidence that someone outside your business took you seriously.',
    ],
    outlets: [
      'Entrepreneur',
      'Success Magazine',
      'USA Today',
      'MSN',
      'Fox Interviewer',
      'NY Weekly',
    ],
    angles: [
      { title: 'Your method, written down', body: 'The actual framework, laid out so a reader could use part of it tonight. Coaches hold this back, fearing they are giving away the product. Editors publish usefulness, and the reader who tries it and gets somewhere is the one who books you.' },
      { title: 'One client, honestly', body: 'A single engagement told with permission and without the highlight reel — what the client came in believing, where it stalled, what changed. Specific stories survive editing. Composite success stories with rounded results do not, and readers in your market can tell the difference.' },
      { title: 'The advice you disagree with', body: 'Your industry repeats things you have watched fail in front of you. Say which one, and why, with your name on it. It is uncomfortable to publish and it is the piece people send to each other, which is the whole point.' },
      { title: 'The career before this', body: 'What you did before you coached — the team you ran, the practice you built, the thing that went wrong and taught you the work. Consultants especially get read on this. It answers the question every buyer has and none of them ask directly.' },
    ],
    objection: "You have probably been sold this before, and possibly by someone who guaranteed Forbes. Much of what gets marketed to coaches is a logo bar linking to nothing. Check ours the way you should check anyone's — click through our case studies and see whether the article is real and still indexed. We also tell you plainly which outlets we can only pitch toward.",
  },
  {
    slug: 'consultants',
    title: 'PR for Consultants',
    navLabel: 'Consultants',
    description: 'Press coverage for independent consultants and firms — winning larger engagements, where we place features, and how it works.',
    audience: 'This page is for independent consultants, boutique advisory firms and fractional executives who get shortlisted against larger competitors and researched before the first call.',
    intro: [
      'Consulting is bought on trust long before anyone reads a scope of work. Your name comes up in a meeting, someone writes it down, and that evening they look you up beside two other names — at least one attached to a much larger firm. What surfaces in those minutes sets the tone of the first call.',
      'We handle the part that is hardest to manufacture on your own — published work, under your name, showing how you think about the problems your buyers have. You answer a short questionnaire and nothing more. Our editorial team writes it, you revise until it sounds like you, and nothing publishes without your sign-off.',
    ],
    whyItWorks: [
      'Almost every consulting engagement starts with a referral and a search. The person who was handed your name checks it before the intro call, and what they find decides whether that call starts warm or starts skeptical.',
      'You are usually being compared with a firm that has far more people than you do. Published thinking is how a small practice shows a method instead of headcount.',
      'Fees get questioned when the buyer cannot tell what they are paying for. An article that lays out how you diagnose a problem moves the conversation from day rate to judgment.',
      'Most of the people approving your contract never meet you. Coverage is something your champion inside the company can forward to the ones who actually decide.',
    ],
    outlets: [
      'Entrepreneur',
      'Business Insider',
      'Fast Company',
      'Inc.',
      'The Business Journals',
      'CEO Weekly',
    ],
    angles: [
      { title: 'The first two weeks', body: 'What you look at before you propose anything: the diagnostic sequence, the questions that change the scope, and the work you talk clients out of. Editors publish it because it is the part of consulting nobody writes down, and buyers read it as proof you have done this before.' },
      { title: 'The engagement that failed', body: 'A project that did not work and the structural reason why — a sponsor who left, a mandate that was never real, a decision made before you arrived. Written without blame it is unusually credible, and it is the piece a serious buyer remembers when the safe choice is the bigger firm.' },
      { title: 'How buyers choose wrong', body: 'Written for the executive assembling a shortlist: what separates consultants who look identical on paper, which questions to ask, which credentials mean little. You end up defining the criteria you are then measured against, which does more for you than any claim about yourself.' },
      { title: 'The sector you own', body: 'One narrow industry, one specific problem, and a piece aimed squarely at the people inside it. Broad business coverage builds a name; a trade-shaped feature written for manufacturers or clinics or logistics operators brings you the buyer who already has the problem you solve.' },
    ],
    objection: 'Most of your work is confidential, and you cannot name the client, the numbers or the outcome. That is real, and it rules out the case-study coverage other industries lean on. It does not rule out the rest. What you know about the pattern — the failures you keep seeing, the sequence you follow — is publishable without a single client detail, and you approve every word first.',
  },
  {
    slug: 'real-estate-agents',
    title: 'PR for Real Estate Agents',
    navLabel: 'Real Estate Agents',
    description: 'Press coverage for realtors and brokers — winning listings, building local authority, and how the process works.',
    audience: 'This page is for residential and commercial agents, brokers and small teams competing for listings in a defined market, who get looked up between the appointment and the signature.',
    intro: [
      'Three agents walk through the same house in the same week. Each one knows the neighborhood, each one has comparable sales and a marketing plan, and the seller picks on something they will never quite articulate — who seems like the bigger name around here.',
      'Press is one of the few things in that conversation you can control. We build the story, our editorial team writes it, and you approve it before it goes anywhere — then it stays online, searchable, for the next seller who types your name in before they call you back.',
    ],
    whyItWorks: [
      'A listing appointment is usually three agents in the same week saying similar things about pricing, photography and staging. A feature in a publication the seller recognizes is the one item on the table the other two do not have.',
      'Sellers check you after you leave. Portal profiles and review counts look alike across every agent in the area, and a published article under your name does not.',
      'Marketing yourself is the proof that you can market a house. A seller sitting through your plan for their property is really asking whether you know how to get attention, and a feature answers that before you open your mouth.',
      'Agents refer across markets constantly. When an agent two states away has a client relocating into your area, they run the same search a seller does before they pass on the name.',
    ],
    outlets: [
      'Real Estate Today',
      'USA Today',
      'MSN',
      'Yahoo Finance',
      'MarketWatch',
      'NY Weekly',
    ],
    angles: [
      { title: 'What your market is doing', body: 'Conditions on your streets, described by someone who is in them every week — what buyers keep asking for, what sellers are slow to accept, which pockets behave differently from the headline story about the region. Editors want local specificity, and you are the one with it.' },
      { title: 'The relocation piece', body: 'Written for the buyer moving in from out of state, months before they choose an agent: neighborhoods and their trade-offs, school and commute realities, the questions people always ask you on their first visit. It reaches them at the stage where nobody has claimed them yet.' },
      { title: 'Where sellers lose money', body: 'The preparation and pricing decisions you watch cost people, told from listing appointments you have actually sat in. It is the rare real estate piece a seller reads to the end, and it makes your next kitchen-table conversation shorter.' },
      { title: 'How a home sells', body: 'Your marketing process for a property, step by step — the sequence, the decisions, what happens in the first week and why. It works as a feature and it works as the thing you leave behind after a listing presentation, which is where most of these get their second life.' },
    ],
    objection: 'Your business is a few zip codes wide, and a national feature will not ring your phone the way a mailer or a portal lead does. True — treat press as a lead source and you will be disappointed. It works on the appointments you already have: the seller deciding between you and two others, and the one checking you out afterward.',
  },
  {
    slug: 'attorneys',
    title: 'PR for Attorneys',
    navLabel: 'Attorneys',
    description: 'Press coverage for lawyers and law firms — building authority with prospective clients and referral sources, and how it works.',
    audience: 'This page is for solo practitioners, partners and boutique firms whose next matter arrives through a referral or a search, and who get vetted before anyone picks up the phone.',
    intro: [
      'Nobody hires a lawyer casually. By the time someone calls your office they have read a great deal, asked someone they trust, and typed your name in beside two or three other firms — and if they came by referral, the person who sent them did the same check first.',
      'What that search returns is the part most firms leave to chance. We develop the angle, our editorial team writes the article, and you review it against your own compliance judgment until it is right — nothing publishes without your sign-off, and what does publish stays there, working quietly, every time your name gets checked again.',
    ],
    whyItWorks: [
      'The best work in most firms arrives from another attorney passing along a conflict or a matter outside their practice. That lawyer is putting their own client relationship on your name, so they check it before making the introduction.',
      'Someone with a legal problem reads a great deal before calling anybody. Firm websites all make the same promises, while a bylined article explaining the thing they are frightened about reads as competence rather than advertising.',
      'Directory badges and ad slots look the same for every firm that buys them. A named article that explains how you actually think about a case does not, and it is the thing a prospective client can still read a year later.',
      'Being on record about your practice area makes you easier to find the next time — for a reporter looking for comment, a panel organizer, or the attorney trying to remember who handles this kind of case.',
    ],
    outlets: [
      'Law & Crime',
      'Law News Day',
      'MSN',
      'The Business Journals',
      'Wall Street Times',
      'Business Insider',
    ],
    angles: [
      { title: 'The law in plain English', body: 'One rule people consistently misunderstand in your practice area, explained for the person living through it rather than for other lawyers. Editors take useful explanation. The reader takes it as the first calm answer they have had, which is often what turns a search into a call.' },
      { title: 'What people do first', body: 'The decisions people make in the days before they hire anyone — the message they send, the form they sign, the conversation they should not have had. You have watched these compound for years, and writing them down is useful to a stranger in a way an ad never is.' },
      { title: 'Commentary on a change', body: 'A new ruling, statute or filing requirement in your area, explained for the businesses or families it lands on. Timeliness is the reason an editor says yes, and a piece dated to the week the change took effect keeps returning in searches long after the news cycle moves on.' },
      { title: 'Written for referring attorneys', body: 'A piece aimed at other lawyers rather than at clients: how a matter in your specialty actually proceeds, where it gets complicated, what a referring firm should expect to happen after they hand it over. Referral relationships are built on exactly this kind of confidence.' },
    ],
    objection: "Your bar has rules about advertising, you cannot discuss a client's matter, and you certainly cannot suggest a result. All of that stands. It also rules out very little of what makes a good article — explanation, context, and judgment about the law itself. You review every draft against your own state's rules, and nothing publishes until you say it can.",
  },
  {
    slug: 'financial-advisors',
    title: 'PR for Financial Advisors',
    navLabel: 'Financial Advisors',
    description: 'Press coverage for financial advisors and wealth managers — building trust with prospective clients, and how the process works.',
    audience: 'For independent RIAs, wealth managers and advisory firm founders whose prospects check them out privately, long before they ever ask a question about fees.',
    intro: [
      'Almost nobody hires an advisor on the strength of the first meeting. They take the referral home, search your name, and read whatever comes back — the firm site, a regulatory record, a headshot on a directory page. That search is where the decision quietly starts.',
      'We write and place articles that turn up in it — a piece under your name, on a publication a prospect recognizes, explaining how you think about money rather than how good you are at managing it. You answer a short questionnaire. Our editorial team does the writing.',
    ],
    whyItWorks: [
      "A referral almost always ends in a search. Your prospect has your name, a firm they have never heard of, and a decision about their life's savings — what comes back on that first page does more work than any brochure.",
      'Accountants and attorneys refer to advisors they can vouch for without exposure. A published article is something a referrer can forward instead of having to make the case for you himself.',
      'Advisory sales cycles are long. Permanent, searchable articles keep answering for you through the months between a first conversation and the transfer paperwork.',
      'A prospect moving a portfolio decides slowly, over months, and mostly without you in the room. A searchable article keeps making your case in that gap between the first meeting and the transfer paperwork.',
    ],
    outlets: [
      'Yahoo Finance',
      'MarketWatch',
      'Benzinga',
      'Business Insider',
      'Forbes',
      'Wall Street Times',
    ],
    angles: [
      { title: 'The question every client asks', body: 'There is one question you answer in almost every review meeting — about taxes, sequencing withdrawals, or what to do with a windfall. Written once, carefully, it becomes the piece a prospect reads at eleven at night before deciding whether to call you.' },
      { title: 'Why you went independent', body: 'Advisors who left a wirehouse or a bank usually left for a reason they have never written down. That decision — what you refused to sell, what you wanted to charge for instead — explains your fee model better than any page on your site can.' },
      { title: 'The niche you actually serve', body: 'Most advisory sites describe everyone. A piece written for business owners two years from an exit, or for physicians carrying training debt into their first high-earning decade, will be read by fewer people and by the right ones. Specificity is what makes it worth publishing.' },
      { title: 'Commentary when markets move', body: "When a rate decision or a market drop has everyone's clients calling at once, reporters want someone who can explain it plainly and will not predict what happens next. That is a standing opportunity rather than a one-off, and it rewards being ready before the news breaks." },
    ],
    objection: 'Compliance is the real obstacle, and we will not pretend otherwise. Performance figures, testimonial-shaped quotes and anything that reads as a prediction are out, and your firm may still say no. What works is educational — how you think, not what you returned. Your CCO reviews the draft with you, revisions are unlimited, and nothing publishes without sign-off.',
  },
  {
    slug: 'medical-practices',
    title: 'PR for Medical Practices',
    navLabel: 'Medical Practices',
    description: 'Press coverage for physicians and medical practices — building patient trust and professional authority, and how it works.',
    audience: 'For physicians, surgeons, dentists and specialty clinic owners whose patients choose them from a search page and a handful of reviews.',
    intro: [
      'A patient who arrived by referral still checks. They type your name, skim the review sites, glance at directory profiles that scraped your credentials years ago, and try to work out from all of it whether you are careful.',
      'Coverage gives that search something with an editor behind it — an article where you explain how you approach a condition, what you tell patients to expect, and who you send elsewhere. We handle the writing. Nothing reaches a publication until you have read it and agreed to it.',
    ],
    whyItWorks: [
      'Patients choose from a results page crowded with directory profiles and star ratings that all look the same. A named article is the one item on it written to an editorial standard rather than assembled from scraped credentials.',
      'Elective and cash-pay work comes with a research window. When a patient is paying directly and weighing three clinics, they read more before booking — so there should be more to read.',
      "Reviews are the one place you cannot answer properly, because privacy rules keep you from discussing a patient at all. An article is where you explain your approach at length, in your own words, without touching anyone's chart.",
      'Referring physicians, hospital committees and the clinicians you are trying to recruit look you up as well. One piece does the professional half of the job alongside the patient half.',
    ],
    outlets: [
      'Healthcare Business Today',
      'USA Today',
      'MSN',
      'Women’s Journal',
      'CEO Weekly',
      "Int'l Business Times",
    ],
    angles: [
      { title: 'The consultation you repeat', body: 'Every practice has the explanation given four times a day in a consult room — what the procedure involves, what recovery really looks like, what it will not fix. Put it in print and patients arrive having already heard it, which changes the appointment before it starts.' },
      { title: 'Who you turn away', body: 'The most persuasive thing a physician can publish is a candid account of who is not a good candidate. Patients have read enough marketing to distrust it. An article that rules people out reads as clinical judgment, and it filters your inquiries before they reach the front desk.' },
      { title: 'How the practice runs', body: 'Appointment length, who answers the phone, whether the surgeon does the follow-up personally — the operational choices behind a practice are the ones patients feel and rarely see explained. A piece about how you built the clinic is a story about care without making a claim about outcomes.' },
      { title: 'A symptom people misread', body: 'General education travels furthest — the pattern patients dismiss for months, the test they assume they have had, the difference between two conditions that get confused. Written as information rather than advice, it reaches readers who are not yet patients and leaves your name attached to the explanation.' },
    ],
    objection: 'The honest constraint is that most of what makes your work compelling belongs to your patients. No case stories without consent, no outcome claims, no superlatives — a piece that ignores that is a liability, not marketing. What is left is still substantial: how you assess, who you decline, what you tell people to expect. You read every line before it publishes.',
  },
  {
    slug: 'ecommerce-brands',
    title: 'PR for Ecommerce Brands',
    navLabel: 'Ecommerce Brands',
    description: 'Press coverage for ecommerce and DTC brands — building trust that lowers acquisition cost, and how the process works.',
    audience: 'For DTC and ecommerce founders and marketing leads selling a considered product to buyers who research a brand before trusting it with a card.',
    intro: [
      'Your buyer sees the ad, gets curious, and leaves to find out whether you are real. They search the brand name, read a couple of reviews, look for anybody outside your own website saying anything about you — and then either come back or do not.',
      'That gap is what coverage is for. It does not compete with paid media and it will not replace it; it is what your paid traffic finds on the way to the checkout. We develop the story, write it, and place it where that search will land.',
    ],
    whyItWorks: [
      'Cold traffic checks. Between the ad and the checkout your buyer opens a new tab, searches the brand name, and decides whether you are a real company — and that search is where the ad spend either converts or evaporates.',
      'A new brand has no shelf and no salesperson. Third-party coverage is the only proof on the page that you did not write yourself.',
      'Retail buyers, marketplace partners and creators vet a brand before committing inventory or their own audience. Having press to send shortens that conversation considerably.',
      'Answer engines summarize a brand from what has been published about it. Product pages and ad copy are not sources; articles are.',
    ],
    outlets: [
      'Entrepreneur',
      'Inc.',
      'Fast Company',
      'Business Insider',
      'MSN',
      'Apple News',
    ],
    angles: [
      { title: 'How the product is made', body: 'Sourcing decisions make good copy when they cost you something — the supplier you left, the material that doubled your unit cost, the test that failed twice before shipping. Editors run manufacturing stories because they are checkable, and buyers read them because everything else on the internet is a claim.' },
      { title: 'The category argument', body: 'Most DTC brands sell against a category norm — a markup, an ingredient, a return policy, a size chart that was never meant to fit anyone. A piece that argues the case, rather than announcing your version of the product, is the one a business editor will actually run.' },
      { title: 'What the first year taught', body: 'Founder lessons age well and keep getting read: the launch that sold out and broke your fulfillment, the channel you overspent on, the SKU you killed. It works because it is specific to your business, which also means nobody else can publish the same article.' },
      { title: 'A launch with news in it', body: 'Retail rollouts, a collaboration, a category the brand had not entered, a genuine reformulation — timed coverage works when something is actually happening, and it is thin when nothing is. We will tell you which one you have before you pay for a campaign built around it.' },
    ],
    objection: 'You are right that a placement will not show up in last-click attribution, and anyone promising a measurable return on one article is guessing. Press is not a performance channel and does not replace one. What it changes is what happens when someone searches your brand name mid-purchase — so watch branded search and returning-visitor behavior, and judge it over quarters rather than days.',
  },
  {
    slug: 'authors',
    title: 'PR for Authors',
    navLabel: 'Authors',
    description: 'Press coverage for authors — building the platform publishers and readers look for, and how the process works.',
    audience: 'This page is for authors — traditionally published, hybrid or self-published — who need people outside their existing readership to know the book exists and to take the person who wrote it seriously.',
    intro: [
      'A manuscript is finished long before anyone is looking for it. The gap between those two moments is where most books quietly disappear — not because the writing failed, but because nobody outside your existing readers had a reason to hear about it.',
      'Coverage closes that gap. We take the idea underneath your book, shape it into a story an editor would run on its own merits, write it, and place it with publications your readers already trust. You approve every word before it goes anywhere.',
    ],
    whyItWorks: [
      'Publishers and agents buy platform as much as manuscript. When someone in acquisitions searches your name, a run of real features answers the question their proposal form asks — who already pays attention to this person, and where.',
      "A book's promotional window is short; a placement does not close. The article is still there when a reader finds you long after launch, through a podcast, a citation, or a search for the subject rather than the title.",
      'Reviews judge the book. A feature carries the idea inside it, so readers who have never seen your cover meet the argument first and go looking for the title second.',
      'Producers and podcast hosts book from what they can read. Published pieces give a producer the angle, the framing and the confidence that you can hold a segment before a pre-interview is ever scheduled.',
    ],
    outlets: [
      'USA Today',
      'MSN',
      'Entrepreneur',
      'Success Magazine',
      'Apple News',
      'NY Weekly',
    ],
    angles: [
      { title: 'The Argument, Stated Plainly', body: 'Take the claim at the center of the book and make it in one piece, with the disagreement left in. Editors run ideas, not summaries of a table of contents — and a reader who argues with you in public is a reader who buys the book.' },
      { title: 'The Chapter Meeting The News', body: 'Something you spent a year researching is suddenly in the headlines. A piece connecting your material to the story people are already following gives an editor a reason to publish this week, and gives you the standing to be asked again next time.' },
      { title: 'What Changed Your Mind', body: 'The belief you held going in and abandoned somewhere in the research. It is the most honest thing an author can publish, it explains why the book exists, and it is far more interesting to a general reader than a description of what the book covers.' },
      { title: 'How The Book Got Made', body: 'Publishing is its own story — the years, the rejections, the choice between a publishing house and doing it yourself. Writers and would-be writers read this kind of piece closely, and it makes you a source on the industry rather than only on your subject.' },
    ],
    objection: 'The honest objection is that press does not sell books, and for a single article that is mostly true — a feature is not a checkout page, and no one should promise you a sales bump. What coverage does is make you findable and credible to the people who decide whether a book gets attention: agents, programmers, producers, and readers who need a second reason to trust you.',
  },
  {
    slug: 'speakers',
    title: 'PR for Speakers',
    navLabel: 'Speakers',
    description: 'Press coverage for professional speakers — getting booked, raising fees, and how the process works.',
    audience: 'This page is for keynote and professional speakers — including executives, operators and subject-matter experts pursuing paid stage work — whose next booking depends on what an event organizer finds when they check.',
    intro: [
      'Bookings rarely turn on the talk itself. They turn on a short stretch of research — an organizer, a committee, sometimes a sponsor, typing your name and deciding in a few minutes whether putting you on their stage is a risk or an easy yes.',
      'That research is what press changes. We develop the idea you speak about into a feature an editor would run, write it, and place it where the people booking you already read. Nothing publishes until you have signed off on it.',
    ],
    whyItWorks: [
      'Organizers shortlist by searching. Long before a call is scheduled, somebody has typed your name to see whether putting you in front of their audience is a safe decision, and what comes back either ends the doubt or creates it.',
      'Fees get approved by people who never see you speak. A committee member or a sponsor needs something to forward, and a feature on a publication they recognize makes the number easier to defend than a highlight reel does.',
      "You get rebooked for a subject, not a speech. Publishing on the same theme repeatedly is what makes the association stick, so your name comes up when that theme lands on next year's agenda.",
      'Events are marketed with your name attached. Press gives the organizer a line for the invitation and a link for the speaker page, which makes promoting the event easier and makes you easier to say yes to.',
    ],
    outlets: [
      'Entrepreneur',
      'Success Magazine',
      'Forbes',
      'CEO Weekly',
      'Fox Interviewer',
      'USA Today',
    ],
    angles: [
      { title: 'The Keynote, In Print', body: 'Your central idea written as a feature that stands without the stage. An organizer weighing you against a shortlist can read the argument before the call and hear how you think — the one thing a highlight reel cannot show.' },
      { title: 'What Your Field Gets Wrong', body: 'A position that would start a real conversation in the room you speak to. Editors publish disagreement, and organizers book speakers who will say something their audience has not heard at every other conference this year. The risk is the point; a safe talk is a forgettable one.' },
      { title: 'The Question Audiences Ask', body: "Whatever comes up in every Q&A, answered properly in print. It shows you have been in front of real rooms rather than pitching to speak in one, and it hands the event's marketing team a line they can quote in the invitation." },
      { title: 'The Experience Behind The Talk', body: 'The work that earned you the topic — the operation you ran, the crisis you handled, the years you spent in the field. Bookers are buying authority as much as delivery, and a profile makes the case for it in a way a bio line never does.' },
    ],
    objection: 'Most bookings come from referrals and a good reel, and no article replaces either — if your video is weak, fix that first. But a referral gets checked. The organizer who was told about you still searches your name before the introduction call, and what they find there decides whether the conversation starts warm or starts with doubt.',
  },
  {
    slug: 'personal-brands',
    title: 'PR for Personal Brands',
    navLabel: 'Personal Brands',
    description: 'Press coverage for personal brands and public figures — owning your search results and building durable authority.',
    audience: 'This page is for public figures whose name is the business — founders, creators, investors and executives with a following — whose reputation gets searched by the people deciding whether to work with them, back them, or hand them a platform.',
    intro: [
      'Anyone can describe themselves well on their own website. The problem is that nobody grants credit for it — a bio is a claim, and the people deciding whether to work with you know the difference between a claim and a third party who found you worth writing about.',
      'So we work the other way around. We find the part of your story that stands up as journalism, write it to editorial standard, and place it with publications that carry weight with the audience you care about. You sign off before anything goes live.',
    ],
    whyItWorks: [
      'Your name is a search result before it is anything else. A permanent feature on an established publication puts something substantial on that page — published somewhere other than your own website — and it stays there.',
      'Audiences on a platform are rented. Accounts get restricted, feeds get reshuffled, and a post is buried within a day; an article does not depend on any platform staying friendly to you.',
      'Answer engines describe you from whatever they can find. When the only sources are your own bio and a handful of posts, the description comes out thin and often wrong — published coverage gives them something attributable to work from.',
      'Boards, panels, partnerships and investors all do a quiet check first. Coverage does the introducing in the days before anyone agrees to a meeting.',
    ],
    outlets: [
      'Forbes',
      'Business Insider',
      'Entrepreneur',
      'MSN',
      'Apple News',
      'Los Angeles Times',
    ],
    angles: [
      { title: 'The Position You Defend', body: 'One argument you are willing to be quoted on for years. A personal brand built on general inspiration is interchangeable; a person known for a specific claim gets called when that subject comes up, by clients and by reporters both.' },
      { title: 'The Middle Of The Story', body: 'Not the origin and not the win — the stretch where it was unclear whether any of it would work. Readers have stopped believing the polished version, and editors have stopped running it. The unflattering middle is what makes a profile credible.' },
      { title: 'What You Turn Down', body: 'The clients, deals or opportunities you decline, and the standard behind the decision. It is unusual enough to be worth publishing, and it tells the people considering working with you more about your judgment than a list of accomplishments would.' },
      { title: 'The Business Behind The Name', body: 'What the operation actually does when you are not on camera — the team, the model, the thing customers pay for. A public figure whose work is vague reads as a persona; showing the machinery underneath turns attention into something people can buy.' },
    ],
    objection: 'If you already have an audience, coverage will not grow it much, and anyone telling you a feature goes viral is selling something. Press does a different job: it holds still. Followers see you on the day you post; a search result meets everyone who checks you later — a client, a partner, a journalist, a platform deciding whether you are safe to host.',
  },
]

export const industryBySlug = new Map(industries.map((i) => [i.slug, i]))

export const industriesPage = {
  eyebrow: 'Industries',
  heading: 'PR by Industry',
  sub: "Press coverage works differently depending on who you sell to. Pick the one that fits and we'll show you what it looks like for your business.",
} as const
